### ISSUE TITLE
github remotes format partially incompatible with remotes package

### ISSUE THREAD

**Issue by ilia-kats** [r-lib/pkgdepends#275]
If a dependency is hosted on GitHub, but its repository name doesn't match the package name, both `pkgdepends` and `remotes` allow explicitly specifying the package name. However, they are incompatible: `pkgdepends` expects a remote of the form `packagename=github::username/repo`, whereas `remotes` expects `github::packagename=username/repo`. This makes it impossible to both allow installation of one's package from GitHub with `remotes` and running a GitHub actions workflow that uses `r-lib/actions/setup-r-dependencies` (which uses `pak` which uses `pkgdepends`)

**Comment by gaborcsardi** [comment]
The `github::` is optional, so `packagename=username/repo` should work for both.

**Comment by ilia-kats** [comment]
Indeed, thank you, now it works. Still, in light of potential addiitonal remotes for pkgdepends (#13, #15, #16) I think the formats should be compatible.

**Comment by gaborcsardi** [comment]
As pkgdepends will get more features in the future, and remotes will not, it is unlikely that the formats will stay fully compatible. That said, pkgdepends should be able to parse the same refs that remotes parses, so I'll fix this here if possible.

**Comment by pawelru** [comment]
Just to add: `<org>/<repo>@*remotes` syntax is currently not supported even though documentation claims to do so:

https://github.com/r-lib/pkgdepends/blob/63479a7f9c5e998cb12e752862ca241b8d9a51b8/tools/doc/pkg-refs.Rmd#L213-L217

This is a dummy example:
```
r$> pkgdepends::new_pkg_installation_proposal("r-lib/cli@*release", config = list(library = tempfile())) -> x
r$> x$solve()
r$> x$get_resolution()$version
ℹ Creating library directory: /var/folders/m1/hrz0h_ls7gz57rc80tnj41t80000gp/T//Rtmpg02Iaz/file66e1a6e1572
[1] "3.6.0.9000"
```

(whereas it should be `"3.6.0"` at the moment of writing this post; also: it's very unlikely to make a release out of development version)

I think I managed to go through the all stack and the problem is that `"release"` slot of `remote_ref` object is being ignored when parsing GH query to download:
https://github.com/r-lib/pkgdepends/blob/63479a7f9c5e998cb12e752862ca241b8d9a51b8/R/type-github.R#L244-L250
