### ISSUE TITLE
Test with all CRAN packages installed

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdepends#50]
If you have installed all CRAN packages, `install.packages()` takes an extremely long time to run. It would be good to test with pkgdepends to make the performance isn't too awful.

**Comment by gaborcsardi** [comment]
Well, this is quite a cumbersome test to run regularly. In any case, I think the only part that depends on the _installed_ packages, is reading in their metadata. pkgdepends does that for all installed packages, because it turns out that this is actually faster than going to the disk individually for every single package.

For ~300 packages this takes about 600ms to do on my macbook. If 15000 packages are installed, and the scaling is linear, which it should be, it still takes only about 3 seconds.

Which could be improved, but I think it is fine for now, until people complain about it.
